apiVersion: v1
kind: Service
metadata:
  name: products-api
  labels:
    api.service: products-api
spec:
  selector:
    api.service: products-api
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000