logging:
  version: 1
  formatters:
    simpleFormatter:
      format: "%(asctime)s %(levelname)-8s %(name)-10s: %(message)s"
  handlers:
    consoleHandler:
      class: "logging.StreamHandler"
      level: "DEBUG"
      formatter: "simpleFormatter"
  root:
    level: "DEBUG"
    handlers: [ "consoleHandler" ]

# Using a shared in-memory sqlite db for dev
db:
  url: "sqlite:///file:dev_db?mode=memory&cache=shared&uri=true"
