networks:
  frontend:
  backend:

secrets:
  db_password:
    file: db_password.txt

services:

  web:
    build: nginx
    networks:
      - frontend
    ports:
      - "80:80"

  productservice:
    networks:
      - frontend
      - backend
    build:
      context: ../../
      dockerfile: ./deploy/web-app/product-service/Dockerfile
    secrets:
      - db_password
    volumes:
      - "./config:/config"

  db:
    image: mysql
    networks:
      - backend
    command: "--init-file /data/application/init.sql --default-authentication-plugin=mysql_native_password"
    volumes:
      - "./db/init.sql:/data/application/init.sql"
      - "db-volume:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=password

volumes:
  db-volume:
