apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip
spec:
  type: ClusterIP
  selector:
    app: nginx-server
  ports:
    - port: 8080
      targetPort: 80


# kubectl apply -f nginx.clusterip.service.yml
# kubectl get services
# curl http://nginx-clusterip:8080 (test connection from inside other pods)
# kubectl delete -f nginx.clusterip.service.yml