apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  type: NodePort
  selector:
    app: nginx-server
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000


# kubectl apply -f nginx.nodeport.service.yml
# kubectl get services
# test external connection to http://localhost:31000
# kubectl delete -f nginx.nodeport.service.yml