apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server
  labels:
    app: nginx-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-server
  template:
    metadata:
      labels:
        app: nginx-server
    spec:
      containers:
        - name: nginx-server
          image: nginx:alpine
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "128Mi" # 128 MB
              cpu: "200m" # 200 millicpu (.2 cpu or 20% of the cpu)


# kubectl create -f nginx.deployment.yml --save-config
# kubectl apply -f nginx.deployment.yml
# kubectl describe deployment nginx-server
# kubectl get deployments --show-labels
# kubectl get deployments -l app=nginx-server
# kubectl scale -f nginx.deployment.yml --replicas=2
# kubectl delete -f nginx.deployment.yml
