apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: nginx-server
  ports:
    - name: "80"
      port: 80
      targetPort: 80


# kubectl apply -f nginx.loadbalancer.service.yml
# kubectl get services
# test external connection to localhost
# kubectl delete -f nginx.loadbalancer.service.yml